
::: {.callout-note}
Textbook reading assignments in the Watson & Breedlove text, *The Mind's Machine* will be indicated by the following shorthand: 'MM pp 3-15'.
This means to read pages 3 to 15.

Note that the text covers material we won't cover in class.
If we don't cover material in class, you aren't responsible for it.
That said, you may find it interesting to learn and know about anyway.
:::

## Week 01 {- #week-01}

### Monday, August 24

*`{r} sched_df$class_1_theme[1]`*

- *Read*: MM pp 3-16
- *Slides*: | [html](slides/wk-01-2026-08-24-intro.qmd) |

### Wednesday, August 26 {-}

*`{r} sched_df$class_2_theme[1]`*

- *Read*: MM pp 3-16
- *Watch*: @National_Geographic2014-gv, @NeuroBriefs2011-pd, @Eames_Office2010-xd
- *Slides*: | [html](slides/wk-01-2025-08-26-hist-methods.qmd) |

### Friday, August 28 {-}

## Week 02 {- #week-02}

### Monday, August 31, 2026 {-}

*`{r} sched_df$class_1_theme[2]`*

- *Read*: MM pp 44-50
- *Watch*: @National-Institute-on-Biomedical-Imaging-and-BioengineeringUnknown-vz, @Video2010-jw, @Understanding_Animal_Research2009-vq
- *Slides*: | [html](slides/wk-02-2025-09-02-methods.qmd) |

### Wednesday, September 2 {-}

*`{r} sched_df$class_2_theme[2]`*

- *Read*: MM pp 27-44
- Extra credit assignment due: [Canvas dropbox](https://psu.instructure.com/courses/2415710/assignments/17605818)
- *Slides*:  | [html](slides/wk-02-2025-09-04-anatomy-I.qmd) |

### Friday, September 04 {-}

## Week 03 {- #week-03}

### Monday, September 07 {-}

**NO CLASS: Labor Day**

### Wednesday, September 09 {-}

*`{r} sched_df$class_1_theme[3]`*

- *Read*: MM pp 16-27
- *Slides*:  | [html](slides/wk-03-2025-09-09-anatomy-II.qmd) |

### Friday, September 11 {-}

*`{r} sched_df$class_2_theme[3]`*

- *Slides*:  | [html](slides/wk-03-2025-09-11-anatomy-III.qmd) |

## Week 04 {- #week-04}

### Monday, September 14 {-}

*`{r} sched_df$class_1_theme[4]`*

- *Read*: MM pp 20-27
- *Slides*:  | [html](slides/wk-04-2025-09-16-cellular-neuro.qmd) |

### Wednesday, September 16 {-}

*`{r} sched_df$class_2_theme[4]`*

- *Read*: MM pp 58-74
- *Slides*:  | [html](slides/wk-04-2025-09-18-neurophys.qmd) |

### Friday, September 18 {-}

## Week 05 {- #week-05}

### Monday, September 21 {-}

*`{r} sched_df$class_1_theme[5]`*

- *Slides*: | [html](slides/wk-05-2025-09-23-exam-rev.qmd) |

### Wednesday, September 23 {-}

*`{r} sched_df$class_2_theme[5]`*

### Friday, September 25 {-}

## Week 06 {- #week-06}

### Monday, September 28 {-}

*`{r} sched_df$class_1_theme[6]`*

- *Read*: MM pp 86-100
- *Slides*:  | [html](slides/wk-06-2025-09-30-neurochem.qmd) |

### Wednesday, September 30 {-}

*`{r} sched_df$class_2_theme[6]`*

### Friday, October 02 {-}

## Week 07 {- #week-07}

### Monday, October 05 {-}

*`{r} sched_df$class_1_theme[7]`*

- *Read*: MM pp 102-106, 122-123
- *Slides*:  | [html](slides/wk-07-2025-10-07-neurochem-II.qmd) |

### Wednesday, October 07 {-}

*`{r} sched_df$class_2_theme[7]`*

- *Read*: MM pp 248-266
- *Slides*:  | [html](slides/wk-07-2025-10-09-hormones.qmd) |

### Friday, October 09 {-}

## Week 08 {- #week-08}

### Monday, October 12 {-}

*`{r} sched_df$class_1_theme[8]`*

- *Slides*:  | [html](slides/wk-08-2025-10-14-evolution.qmd) |
- *Watch*: @Scale-2023-gp

### Wednesday, October 14 {-}

*`{r} sched_df$class_2_theme[8]`*

- *Read*: MM pp 124-134, 145
- *Slides*:  | [html](slides/wk-08-2025-10-16-development.qmd) |

### Friday, October 16 {-}

## Week 09 {- #week-09}

### Monday, October 19 {-}

*`{r} sched_df$class_1_theme[9]`*

- *Slides*:  | [html](slides/wk-09-2025-10-21-exam-rev.qmd) |

### Wednesday, October 21 {-}

*`{r} sched_df$class_2_theme[9]`*

### Friday, October 23 {-}

## Week 10 {- #week-10}

### Monday, October 26 {-}

*`{r} sched_df$class_1_theme[10]`*

- *Read*: MM pp 106-108, 412-405
- *Slides*:  | [html](slides/wk-10-2025-10-28-psychopathology-I.qmd) |

### Wednesday, October 28 {-}

*`{r} sched_df$class_2_theme[10]`*

- *Read*: MM pp 106-108, 386-394
- *Slides*:  | [html](slides/wk-10-2025-10-30-psychopathology-II.qmd) |

### Friday, October 30 {-}

## Week 11 {- #week-11}

### Monday, November 02 {-}

*`{r} sched_df$class_1_theme[11]`*

### Wednesday, November 04 {-}

*`{r} sched_df$class_2_theme[11]`*

- *Read*: MM pp 356-369
- *Slides*:  | [html](slides/wk-11-2025-11-06-emotion-I.qmd) |

### Friday, November 06

## Week 12 {- #week-12}

### Monday, November 09 {-}

*`{r} sched_df$class_1_theme[12]`*

- *Read*: MM pp 375-383
- *Slides*:  | [html](slides/wk-12-2025-11-11-emotion-II.qmd) |

### Wednesday, November 11 {-}

*`{r} sched_df$class_2_theme[12]`*

- *Read*: MM pp 148-157
- *Slides*:  | [html](slides/wk-12-2025-11-13-sensory-systems.qmd) |

### Friday, November 13

## Week 13 {- #week-13}

### Monday, November 16 {-}

*`{r} sched_df$class_1_theme[13]`*

- *Slides*:  | [html](slides/wk-13-2025-11-18-somatosensation.qmd) |

### Wednesday, November 18 {-}

*`{r} sched_df$class_2_theme[13]`*

- *Read*: MM pp 148-157
- *Slides*:  | [html](sliwk-13-2025-11-20-action-I.qmd) |

### Friday, November 20

## Thanksgiving Break

**NO CLASS**

## Week 14 {- #week-14}

### Monday, November 30 {-}

~~Exam 3~~ (rescheduled for Thursday)

### Wednesday, December 02 {-}

*Exam 3*

::: {.callout-note}
Slides and material for the following topic are provide here for students' reference.

*Action II*

- *Slides*:  | [html](slides/wk-15-2025-11-04-action-II.qmd) |

:::

### Friday, December 04

## Week 15 {- #week-16}

### Monday, December 07 {-}

*`{r} sched_df$class_1_theme[16]`*

- *Slides*:  | [html](slides/wk-15-2025-12-09-memory.qmd) |

### Wednesday, December 09 {-}

*`{r} sched_df$class_2_theme[16]`*

- *Slides*:  | [html](slides/wk-15-2025-12-11-cerebral-symphony.qmd) |

### Friday, December 11

## Finals Week {- #finals-week}

*Exam 4 (Final)* TBD